server:
  port: 8080
spring:
  application:
    name: foodstorage

  devtools:
    livereload:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/fooddb
    username: food_user
    password: pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true