CREATE SEQUENCE T_CONTAINER_SEQ increment by 1 start with 1;

CREATE TABLE T_CONTAINER(
    ID BIGINT not null default nextval('T_CONTAINER_SEQ'),
    NAME varchar(255) not null,
    STORAGE_ID BIGINT not null,
    DESCRIPTION TEXT,
    ARCHIVED boolean not null default false,

    CREATED_AT timestamp not null DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp not null DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY varchar(100),
    UPDATED_BY varchar(100),

    CONSTRAINT CONTAINER_PK PRIMARY KEY (ID),

    CONSTRAINT CONTAINER_STORAGE_FK
        FOREIGN KEY (STORAGE_ID)
        REFERENCES T_STORAGE(ID)
);

CREATE INDEX IDX_CONTAINER_STORAGE_ID ON T_CONTAINER(STORAGE_ID);
