CREATE SEQUENCE T_HOUSEHOLD_MEMBER_SEQ increment by 1 start with 1;

CREATE TABLE T_HOUSEHOLD_MEMBER (
  ID BIGINT not null default nextval('T_HOUSEHOLD_MEMBER_SEQ'),
  HOUSEHOLD_ID BIGINT not null,
  USER_ID BIGINT not null,
  ROLE VARCHAR(50) not null default 'MEMBER' CHECK (ROLE IN ('MEMBER', 'OWNER')),
  ARCHIVED BOOLEAN not null default false,

  CREATED_AT timestamp not null DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT timestamp not null DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY varchar(100),
  UPDATED_BY varchar(100),

  CONSTRAINT T_HOUSEHOLD_MEMBER_PK PRIMARY KEY (ID),

  CONSTRAINT HOUSEHOLD_MEMBER_HOUSEHOLD_FK
    FOREIGN KEY (HOUSEHOLD_ID)
    REFERENCES T_HOUSEHOLD(ID),

  CONSTRAINT HOUSEHOLD_MEMBER_USER_FK
    FOREIGN KEY (USER_ID)
    REFERENCES T_USER(ID)
);

CREATE INDEX IDX_HOUSEHOLD_MEMBER_HOUSEHOLD_ID
    ON T_HOUSEHOLD_MEMBER(HOUSEHOLD_ID)
    WHERE ARCHIVED = false;

CREATE INDEX IDX_HOUSEHOLD_MEMBER_USER_ID
    ON T_HOUSEHOLD_MEMBER(USER_ID)
    WHERE ARCHIVED = false;
