CREATE SEQUENCE T_STORED_ITEM_SEQ increment by 1 start with 1;

CREATE TABLE T_STORED_ITEM(
    ID BIGINT not null default nextval('T_STORED_ITEM_SEQ'),
    CONTAINER_ID BIGINT not null,
    PRODUCT_ID BIGINT not null,
    ARCHIVED boolean not null default false,
    EXPIRY_DATE DATE not null default CURRENT_DATE,
    QUANTITY_VALUE INTEGER not null default 1,
    CREATED_AT TIMESTAMP not null default CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP not null default CURRENT_TIMESTAMP,

    CONSTRAINT STORED_ITEM_PK PRIMARY KEY (ID),

    CONSTRAINT STORED_ITEM_CONTAINER_FK
        FOREIGN KEY (CONTAINER_ID)
        REFERENCES T_CONTAINER(ID),

    CONSTRAINT STORED_ITEM_PRODUCT_FK
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES T_PRODUCT(ID)
);

CREATE INDEX IDX_STORED_ITEM_CONTAINER_ID ON T_STORED_ITEM(CONTAINER_ID);
CREATE INDEX IDX_STORED_ITEM_PRODUCT_ID ON T_STORED_ITEM(PRODUCT_ID);
CREATE INDEX IDX_STORED_ITEM_EXPIRY_DATE ON T_STORED_ITEM(EXPIRY_DATE);