CREATE SEQUENCE T_STORAGE_SEQ increment by 1 start with 1;

CREATE TABLE T_STORAGE(
    ID BIGINT not null default nextval('T_STORAGE_SEQ'),
    NAME varchar(255) not null,
    HOUSEHOLD_ID BIGINT not null,
    DESCRIPTION TEXT,
    ARCHIVED boolean not null default false,

    CREATED_AT timestamp not null DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp not null DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY varchar(100),
    UPDATED_BY varchar(100),

    CONSTRAINT STORAGE_PK PRIMARY KEY (ID),

    CONSTRAINT STORAGE_HOUSEHOLD_FK
        FOREIGN KEY (HOUSEHOLD_ID)
        REFERENCES T_HOUSEHOLD(ID)
);

CREATE INDEX IDX_STORAGE_HOUSEHOLD_ID_ACTIVE
    ON T_STORAGE(HOUSEHOLD_ID)
    WHERE ARCHIVED = false;